### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by mine-tech-oficial** [finalclass/htmz#1]
Hello!
Whenever I try to compile the package, the compiler says the following

```
Compiling htmz
error: Unknown module field
  ┌─ /[CENSORED]/build/packages/htmz/src/htmz/selector_parser.gleam:6:28
  │
6 │ import gleam/option.{None, Option, Some, map}
  │                            ^^^^^^ Did you mean `then`?

The module `gleam/option` does not have a `Option` value
```

I think it should be `type Option` instead of just `Option`

**Comment by zoilorys** [comment]
@mine-tech-oficial , feels like this project is abandoned, which is sad, cause I feel like this is the proper way to build templates is functional Elixir-ish gleam way. I personally like this more than nakai way.
@finalclass , can you please confirm if you're going to continue working on this library, or maybe someone can overtake it to maintain it further?

**Comment by finalclass** [comment]
I will try to fix the bug today. The library hasn't been adjusted to the new gleam version - that might be the reason for the issue. 

I'm not done with gleam:) so for now I can maintain the repo. Somehow I missed this bug report.
Of course PRs are welcomed:)

**Comment by finalclass** [comment]
Fixed with https://github.com/finalclass/htmz/commit/f4c351db3e819cfc521d82f40672f3f6a6b7920b
Version 0.1.3 has been published. https://hex.pm/packages/htmz/0.1.3
The issue was with the changes introduced in recent versions of Gleam.
